# Generated by Django 5.1.1 on 2024-12-21 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('mark_delete', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimelineNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('node_title', models.CharField(blank=True, max_length=20, null=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('mark_delete', models.BooleanField(default=False)),
                ('time_line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timeline.timeline')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
