# Generated by Django 5.1.1 on 2025-02-07 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('remainder', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnchorCheckPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('all_task_done', models.BooleanField(default=False)),
                ('daily_done', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('dailyparent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timeline.dailyparent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('done', models.BooleanField(default=False)),
                ('remainder', models.CharField(blank=True, max_length=20, null=True)),
                ('anchorcheckpoint', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timeline.anchorcheckpoint')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
