# Generated by Django 5.1.1 on 2025-02-07 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_dailyparent_anchorcheckpoint_listitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='anchorcheckpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timeline.anchorcheckpoint'),
        ),
    ]
