# Generated by Django 5.1.1 on 2025-02-10 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_alter_listitem_anchorcheckpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('all_task_done', models.BooleanField(default=False)),
                ('daily_done', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('remainder', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='anchorcheckpoint',
            name='dailyparent',
        ),
        migrations.RemoveField(
            model_name='listitem',
            name='anchorcheckpoint',
        ),
        migrations.AddField(
            model_name='listitem',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timeline.parenttask'),
        ),
        migrations.DeleteModel(
            name='DailyParent',
        ),
        migrations.DeleteModel(
            name='AnchorCheckPoint',
        ),
    ]
