# Generated by Django 5.1.1 on 2024-09-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverletter',
            name='mark_delete',
            field=models.BooleanField(default=False),
        ),
    ]
