# Generated by Django 5.1.1 on 2025-02-11 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_username_alter_user_email'),
        ('coverit', '0002_alter_coverletter_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverletter',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
