# Generated by Django 5.1.1 on 2025-02-11 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coverit', '0004_coverletter_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverletter',
            name='user',
        ),
    ]
