"""
Django settings for pilot_products project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()
from colorama import Fore
import dj_database_url
from colorama import init, Fore
from urllib.parse import urlparse
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'coverit',
    'core',
    'webnode',
    'accounts',
    'generators',
    'timeline',
    'django.contrib.sites',  # Required for django-allauth

    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    # Only Google provider
    'allauth.socialaccount.providers.google',
    
   
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = 'pilot_products.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'pilot_products.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


# Initialize colorama
init(autoreset=True)

BASE_DIR = Path(__file__).resolve().parent.parent


tmpPostgres = urlparse(os.getenv("DATABASE_URL"))
# Environment variables for database selection
USE_MYSQL = os.getenv('USE_MYSQL', 'False').lower() in ('true', '1', 't')
USE_POSTGRESQL = os.getenv('USE_POSTGRESQL', 'False').lower() in ('true', '1', 't')
# Define the base directory for SQLite
BASE_DIR = Path(__file__).resolve().parent

# Database configuration based on the environment variables
if USE_MYSQL:
    db_name = os.getenv('MYSQL_DB_NAME')
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': db_name,
            'USER': os.getenv('MYSQL_DB_USER'),
            'PASSWORD': os.getenv('MYSQL_DB_PASSWORD'),
            'HOST': os.getenv('MYSQL_DB_HOST'),
            'PORT': '3306',
        }
    }
    print(f"{Fore.GREEN}Using MySQL database: {db_name} (True)")

elif USE_POSTGRESQL:
    db_name = tmpPostgres.path.replace('/', ''),
    DATABASES = {
       'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': tmpPostgres.path.replace('/', ''),
        'USER': tmpPostgres.username,
        'PASSWORD': tmpPostgres.password,
        'HOST': tmpPostgres.hostname,
        'PORT': 5432,
    }

    }
    print(f"{Fore.GREEN}Using PostgreSQL database: {db_name} (True)")

else:
    db_name = BASE_DIR / 'db.sqlite3'
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME':'db.sqlite3',
        }
    }
    print(f"{Fore.GREEN}Using SQLite db")

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
MEDIA_ROOT  = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
STATIC_URL = 'static/'
STATIC_ROOT =  "staticfiles" # Ensure BASE_DIR is defined
STATICFILES_DIRS = ["static"
]
 # Your development static folder
# Optional: for better caching
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTHENTICATION_BACKENDS = (
    # 'django.contrib.auth.backends.ModelBackend',
    'accounts.backends.CustomBackend',
    'allauth.account.auth_backends.AuthenticationBackend',  # Allauth backend
    
)
AUTH_USER_MODEL = 'accounts.User'
SITE_ID = 1  # Required for django-allauth
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        # For each OAuth based provider, either add a ``SocialApp``
        # (``socialaccount`` app) containing the required client
        # credentials, or list them here:
        'APP': {
            'client_id': os.getenv('GOOGLE_OAUTH_CLIENT_ID'),
            'secret': os.getenv('GOOGLE_OAUTH_CLIENT_SECRET'),
            'key': '',
             "settings": {
                    # You can fine tune these settings per app:
                    "scope": [
                        "profile",
                        "email",
                    ],
                    "auth_params": {
                        "access_type": "offline",
                    },
                },
        },
        'SCOPE': ['email', 'profile'],
        'AUTH_PARAMS': {
            'access_type': 'offline',  # Ensures refresh token
            'prompt': 'consent',  # Forces Google to show consent screen
        }
    }
}
# Ensure email is used for login
ACCOUNT_AUTHENTICATION_METHOD = "email"  # Use email instead of username
ACCOUNT_EMAIL_REQUIRED = True  # Ensure email is required
ACCOUNT_USERNAME_REQUIRED = False  # Disable username requirement
ACCOUNT_USER_MODEL_USERNAME_FIELD = None  # Remove username field dependency
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = True
ACCOUNT_ADAPTER = "allauth.account.adapter.DefaultAccountAdapter"
ACCOUNT_SIGNUP_DISABLED = False  # Ensure this is set to False


# Redirect after login
LOGIN_REDIRECT_URL = "/"  # Change this to your desired route

# Redirect after logout (optional)
LOGOUT_REDIRECT_URL = "/"  # Redirect users to homepage after logout

FLASH_AI_KEY = os.getenv("GEMINI_API_KEY")